% plotting the source and fates particles from various runs. 
% this script was generated by Z. Feng (WHOI, now ECNU) and R Ji (WHOI)
%modified by JJS

clc
close all
%%
cd 'D:\Sand_Lance_Dispersal_Modeling\Matlab_Code'
load Stell_Polygon.mat
load NS_Polygon.mat
load GB_Polygon.mat

cd 'D:\Sand_Lance_Dispersal_Modeling\data_files'
load GOM3_coast.mat
load GOM3_grid.mat
load xy_coastline.mat
path2mydata='E:\SL_Particle_Tracking_Runs\Stellwagen\Forward_New';

cd(path2mydata);

x_gom3 = mGRID.x;
y_gom3 = mGRID.y;
h_gom3 = mGRID.h;
lon_gom3 = mGRID.lon;
lat_gom3 = mGRID.lat;
addpath 'D:\Sand_Lance_Dispersal_Modeling\data_files\mygeodata'
% ETOPO-1 bathymetry
 file = 'exportimage_NE.nc';
 [LAT,LON] = meshgrid(ncread(file,'lat'),ncread(file,'lon'));
 z = double(ncread(file,'Band1'));
%%
LonMax = ceil(max(lon_gom3));
LonMin = floor(min(lon_gom3));
LatMax = ceil(max(lat_gom3));
LatMin = floor(min(lat_gom3));

deg = 0.05;
LonGrid = LonMin : deg : LonMax;
LatGrid = LatMin : deg : LatMax;
NumThrd = 1;

%% multiyear backward run in the month of August

nRuns = 32;  % number of daily runs
nDays = 75; % number of days backward tracked
np = 4920;  % number of particles per day of release
addpath 'D:\Sand_Lance_Dispersal_Modeling\data_files\sp_proj';
addpath 'D:\Sand_Lance_Dispersal_Modeling\data_files';
Month=[1 12];
Year=[2004 2016];
tic
for q = 1:27% 1-year takes ~220 s
    year=Year(q);
  for  ii = 1:1:2
    month=Month(ii);
    year
    if  month== 1
                dend=24;
                dstart=1;
	else if month==12 
            dstart=24;
                dend=31;
        end
    end
    for Day = dstart:1:dend  
        
        Day
        
    
    
    
    YearStr = num2str(year);
      
    X_loc = nan(np,nDays,nRuns);
    Y_loc = nan(np,nDays,nRuns);

    if month < 10
        MonthStr = ['0',num2str(month)];
    else
        MonthStr = num2str(month);
    end
    
   for day = 1 :1: 32

       if Day < 10
           DayStr = ['0',num2str(Day)];
       else
           DayStr = num2str(Day);
       end 
    
       file = [path2mydata,'\',YearStr,'\',YearStr,MonthStr,DayStr,'\fiscm_group_001.nc'];

       x_loc = ncread(file,'x',[1 2],[np nDays]);
       y_loc = ncread(file,'y',[1 2],[np nDays]);
       
       X_loc(:,:,day) = x_loc;
       Y_loc(:,:,day) = y_loc;
   
   end
    end
  end

        [Lon_loc,Lat_loc] = sp_proj('1802','inverse',X_loc,Y_loc,'m');
       [Stell_PolyLon, Stell_PolyLat]=sp_proj('1802','inverse',Stell_Polygon(:,1),Stell_Polygon(:,2),'m');
       [NS_PolyLon, NS_PolyLat]=sp_proj('1802','inverse',NS_Polygon(:,1),NS_Polygon(:,2),'m');
       [GB_PolyLon, GB_PolyLat]=sp_proj('1802','inverse',GB_Polygon(:,1),GB_Polygon(:,2),'m');

       [X_AXIS,Y_AXIS,XY_plot] = density_xy(Lon_loc(:),Lat_loc(:),LonGrid,LatGrid);
       XY_plot(XY_plot < NumThrd) = nan;
   
     set(0,'DefaultFigureVisible','off')

       figure(year)
        hold on
        dens=log10(XY_plot/np/nDays/nRuns);
        dens(dens<-7)=NaN;
        pcolor(X_AXIS,Y_AXIS,dens);
        hold on
  
        plot(Stell_PolyLon,Stell_PolyLat,'k-','linewidth',2)
        plot(NS_PolyLon,NS_PolyLat,'k-','linewidth',2)
        plot(GB_PolyLon,GB_PolyLat,'k-','linewidth',2)

        caxis([-7 -2])
        set(gca,'fontsize',12)
        shading flat
        colormap('jet(30)')
        colorbar('Location','NorthOutSide','fontsize',14,...
                 'ticks',-7:-1,'ticklabels',{'<10^{-7}','<10^{-6}','<10^{-5}','<10^{-4}','10^{-3}','10^{-2}','10^{-1}'})
        contour(LON,LAT,z,[-100 -100],'-','color',[0.2 0.2 0.2])
        hold on
        scatter(Lon_loc(1000,:,1), Lat_loc(1000,:,1),45,'MarkerEdgeColor',[0 0 0],...
              'MarkerFaceColor',[0.5 0.5 0.5],...
              'LineWidth',0.5)
        
        hold on
               states = shaperead('usastatehi', 'UseGeoCoords', true);
geoshow(states, 'DefaultFaceColor', 'black', ...
                'DefaultEdgeColor', 'black');
            hold on
CL=shaperead('D:\Sand_Lance\Sandlance Mapping Code-20200211T181943Z-001\Sandlance Mapping Code\PROVINCE.SHP')
mapshow(CL,'FaceColor', 'black', ...
                'DefaultEdgeColor', 'black');
            
geoshow(states, 'FaceColor', 'black')  
hold on 

        set(gca,'xtick',[-76 -72 -68 -64 -60 -56])
        set(gca,'xticklabel',{'76^{o}W','72^{o}W','68^{o}W','64^{o}W','60^{o}W','56^{o}W'})
        set(gca,'ytick',[35 37 39 41 43 45])
        set(gca,'yticklabel',{'35^{o}N','37^{o}N','39^{o}N','41^{o}N','43^{o}N','45^{o}N'}) 
        title(['Stellwagen 75-day forward track from December/January ',YearStr],'fontsize',12)
        set(gca,'fontsize',12)
        box on
        axis([-75 -60 37 46])
        set(gca,'fontsize',12)
        cd 'D:\Sand_Lance_Dispersal_Modeling\Ch3_Manuscript\Revisions\Figures\Stell\Forward'
        saveas(gcf,['Pathway_Probability_Stell_Forward_All_Figure_220202_',YearStr,MonthStr,'.png'])
        close   
end
toc

  
